### ISSUE TITLE
Make the quests journal accessible

### ISSUE THREAD

**Issue by GuideDev** [HearthstoneAccess/HearthstoneAccess#12]
Note: quests can already be completed and players can read them once per day when the game opens via the reminder popup.

**Comment by paxcoder** [comment]
shame that we can't access it.
The game works like in demo mode sadly.

**Comment by Timtam** [comment]
@paxcoder as you can already see, the developer of HearthstoneAccess created the issue him/herself and thus already knows about it. Just give it some time, creating this mod is a highly daunting and time consuming task, it will come eventually.

**Comment by GuideDev** [comment]
Done.
