### ISSUE TITLE
Add support for selecting hero power

### ISSUE THREAD

**Issue by Timtam** [HearthstoneAccess/HearthstoneAccess#25]
I know that the book of mercenaries is not yet supported, but the mercenary Guff from game 2 onward allows you to select one out of four hero powers to be your hero power for the game when starting a game. That selection is not yet accessible.

**Comment by GuideDev** [comment]
Hi @Timtam. I'm aware of this but it's part of making the Book of Mercenaries accessible. Closing in favor of https://github.com/HearthstoneAccess/HearthstoneAccess/issues/3
