### ISSUE TITLE
Add support for tradeable cards

### ISSUE THREAD

**Issue by Timtam** [HearthstoneAccess/HearthstoneAccess#29]
There are cards which do have the Tradeable effect: Shuffle them into your deck, pay 1 mana and draw a card. You can play them right now, but not use the Tradeable effect. When playing a Tradeable card without having enough mana to actually play them, you already get the sound that plays whenever you selected a card and are deciding if you really want to play it, but you cannot select the tradeable option, but only the cast option by pressing enter, and that obviously fails with an error message because there is not enough mana to cast it.
Example card: Fire Sale.

**Comment by GuideDev** [comment]
Done and released in the new version. Thanks for reporting.
