### ISSUE TITLE
Shift + F pressed just before end of turn is executed at start of next turn

### ISSUE THREAD

**Issue by SamKacer** [HearthstoneAccess/HearthstoneAccess#44]
Hello,

had this bug happen to me earlier today. Probably fairly rare to trigger it, but it could cost a player a game in the rare circumstance when it does occur.

Had 2 minions on board that were ready to attack. Timer was counting down and pressed shift + F just second before it expired. I heard the first minion was selected to attack (heard it raised off the board and its "battle cry"), but it didn't manage to attack.

Both minions survived opponent's turn and at the start of my turn, both of them attacked face automatically  before I even pressed any buttons.

**Comment by GuideDev** [comment]
Nice catch! This will be fixed in the next release. Thanks for reporting!

**Comment by GuideDev** [comment]
Done.
