### ISSUE TITLE
Make the frame rate options menu accessible

### ISSUE THREAD

**Issue by pitermach** [HearthstoneAccess/HearthstoneAccess#61]
One of the new features Blizzard added in the recent patch is a menu to choose the game's frame rate. They also changed the default rate the game runs at to be slower than it used to be. This is very noticeable in Battlegrounds where it feels like the game is constantly lagging. It might be also causing other features in the mod like card trading to not work consistently (#60)

While it's possible to override this by editing the game configuration manually the articles I read suggest hearthstone updates can sometimes revert this change so it would be better if the mod made the official way of adjusting this accessible.

**Comment by GuideDev** [comment]
Done in 23.4.0. Thanks for the heads up!
